name: older_pytorch
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - cudatoolkit=9.0
  - bcolz=1.2.0
  
  - pip
  - pip:
    # Install legacy PyTorch via direct wheel URLs
    - https://download.pytorch.org/whl/cu90/torch-0.3.1-cp36-cp36m-linux_x86_64.whl
    - torchvision==0.2.1 -f https://download.pytorch.org/whl/cu90/torch_stable.html
    
    # Other dependencies
    - torchtext==0.2.3
    - cython==0.29.24
    - opencv-python==4.1.2.30
    - pillow==8.4.0
    - MarkupSafe<2.1
    - jinja2<3.0
    - requests==2.27.1
    - packaging<21.0
    - typing-extensions<4.0
    - sentencepiece==0.1.83
    - numpy==1.16.6
    - pandas==1.1.5
    - scipy==1.5.4
    - tqdm==4.64.1
    - fastai==0.7